Homework33
ViraRiefertDev/JavaLessonsAIT pull request #9
Opened 2024-05-16 09:22 UTC by ViraRiefertDev

2024-05-16 12:49 UTC, zimmermann2013 requested changes

2024-05-16 12:49 UTC, zimmermann2013 commented on src/main/java/homework/homework33/ClothingManager.java
> +               return clothingItems.remove(item);
Удаление через итератор в данном случае безопаснее, потому что при одновременной попытке удаления и добавления элемента может выскочить ConcurrentModificationException

2024-05-16 12:49 UTC, zimmermann2013 commented on src/main/java/homework/homework33/ClothingManager.java
> +        double cheapestprice = clothingItems.getFirst().getPrice();
А если первого элемента не существует? Получим сообщение об ошибке

2024-05-17 21:11 UTC, ViraRiefertDev commented on src/main/java/homework/homework33/ClothingManager.java
> +               return clothingItems.remove(item);
Исправлено

2024-05-17 21:11 UTC, ViraRiefertDev commented on src/main/java/homework/homework33/ClothingManager.java
> +        double cheapestprice = clothingItems.getFirst().getPrice();
метод доработан

2024-06-02 21:30 UTC, merged